vich_uploader:
    db_driver: orm

    mappings:
       products:
           uri_prefix: /img/produits
           upload_destination: '%kernel.project_dir%/public/img/produits'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
